### PR TITLE
README Formatting

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
[Badge Suggestions]: https://img.shields.io/badge/Ｒｅｐｏｓｉｔｏｒｙ_Ｓｕｇｇｅｓｔｉｏｎｓ-4b781e?style=for-the-badge&logoColor=white&logo=GitHub&labelColor=609926
[Badge Changes]: https://img.shields.io/badge/Ｃｈａｎｇｅｓ-9e122a?style=for-the-badge&logoColor=white&logo=GitLFS&labelColor=D81939
[Badge GitHub]: https://img.shields.io/badge/ＧｉｔＨｕｂ_Ｎｅｗｃｏｍｅｒｓ-be2e47?style=for-the-badge&logoColor=white&logo=BitWarden&labelColor=FD3A5C
[Badge Robot]: https://img.shields.io/badge/Ｉ＇ｍ_Ｈｕｍａｎ-8c3b63?style=for-the-badge&logoColor=white&logo=RuboCop&labelColor=c84f8c
[Badge Ask]: https://img.shields.io/badge/Ｐｌｅａｓｅ_Ａｓｋ_Ｍｅ-4e2760?style=for-the-badge&logoColor=white&logo=AskUbuntu&labelColor=73398D
[Badge Info]: https://img.shields.io/badge/Ｉｎｆｏｒｍａｔｉｏｎ-01434e?style=for-the-badge&logoColor=white&logo=InternetArchive&labelColor=006272

[Button MarkedDown]: https://img.shields.io/badge/MarkedDown-00b2ff?style=for-the-badge&logoColor=white&logo=Markdown

[License Badges]: https://github.com/MarkedDown/Licenses
[Widgets]: https://github.com/MarkedDown/Disable/blob/main/Features/Widgets.md
[Tabs]: https://github.com/MarkedDown/Disable/blob/main/Features/Tabs.md
[Wiki]: https://github.com/MarkedDown/Wiki
[MarkedDown]: https://github.com/MarkedDown 'How to better use Markdown'

<br>
<br>

<div align = center>

[<kbd> <br> Please Check The **Preview** <br> </kbd>][Preview]

</div>
  
<br>
<br>

## ![Badge Suggestions]

  <br>

- **Update Description**

  `Plumy the Mindustry gradle plugin.`

  <br>

- ***[Disable unused Widgets][Widgets]***:

  - `Releases`

  <br>

- ***[Disable unused Tabs][Tabs]***:

  - `Projects`

  - `Wiki`
  
  <br>

<br>
<br>

## ![Badge Changes]

- General formatting / spacing

- Added license badge

- Added quicklinks

- Moved usage / documentation hub into dedicated files

  *Btw, the links to your GitHub Pages site for groovy & kotlin dsl are broken, well the pages are.*

- Fixed license filename

<br>
<br>

## ![Badge Ask]

- ***If you have any questions.***

- ***In case you do not agree with some of the changes made in this PR***,
  *please first let me know about them, before disregarding it entirely so*
  *we can possibly find a middle ground and have it not go to waste.*

<br>
<br>

## ![Badge Robot]

<kbd> <br>            No, I'm not a robot.            <br> </kbd>

<kbd> <br>    Yes, you are not the first.    <br> </kbd>

<kbd> <br>     I just made a PR template.     <br> </kbd>

<br>
<br>

## ![Badge Info]

If you want to know more about **Markdown** check out:

<br>

                            [![Button MarkedDown]][MarkedDown]

<br>
<br>

[Preview]: https://github.com/ElectronicsArchiver/mgpp

### CODE REVIEW

**Comment by liplum** [comment]
ありがとうございます！
It looks pretty nice and neat, but since `mgpp` is made for modding, I don't think this pull request is very suitable for programmers, aka. modders, at present.

First of all, I'm poor at visual design, so my words might be not convincing.

## Readme
Readme is the first impression of a repo.
The viewers, in this case, almost of them are modders, are seeking a gradle plugin to free themself from their busy work on  building a mod and get a quick starting.

> Icon is placed on the top.

Because [preview.png](https://github.com/ElectronicsArchiver/mgpp/blob/master/GFX/preview.png) is for GitHub repo preview, it's too large as a header. I will shrink it and create a dedicated image soon.

> Badges 

`Website` isn't a good name for the instruction that teach users how to use `mgpp`.
It's a bit confusing that I even thought you had remade a new website for it, in other words, I didn't understand whether it was a descriptive usage document or a colorful showcase.

It could be `instruction` or `Get Started`.

That has hidden too much information behind a `documentation` badges.
When a new viewer want to know `mgpp`, they have to jump around with the funny hyperlink, which I even didn't think the badges is a hyperlink because it's not a verb, such as `Read Document` or stands for a hyperlink.

> Features Graph

I will resort them ordered by its importance for modding soon.

## Documentation.md

Since I have made an instruction, it's redundant and obese to make other hyperlinks for only one purpose that tells viewers how to use this plugin.
Then I will delete them.


## Conclusion
The badges should be not only informative but simplified, such as `User Guide`, `JavaDoc`, `Mod Template`.
There is no need to make a lot of hyperlinks jumping over the repo.

**Comment by liplum** [comment]
`Disable unused Tabs` is done.

**Comment by ElectronicsArchiver** [comment]
<br>

> which I even didn't think the badges is a hyperlink at first sight because it's not a verb, such as Read Document or stands for a hyperlink.

It is absolutely common to have nouns for button names,
just look at GitHub itself, the profile / front page has:

- `Pull requests`
- `Issues`
- `Marketplace`
- `Overview`
- `Repositories`
- `Projects`
- `Packages`
- `Stars`
- ...

<br>

> I will resort them ordered by its importance for modding soon.

Sure~

<br>

> Also, docs-shared/ folder is for sharing the same content in different pages in the instruction website with mkdocs.

I see, wasn't sure, what it was about.

<br>

> Release isn't an unused widget, and I have the plan for another purpose.

Right now it is, but if you plan on using it sure.

<br>

> The badges should be not only informative but simplified, such as User Guide, JavaDoc, Mod Template.

So you rather want those links as buttons on the README?

<br>

> There is no need to make a lot of hyperlinks jumping over the repo.

`3` is not what I consider a lot, but sure.

<br>

**Comment by ElectronicsArchiver** [comment]
@liplum better?

**Comment by liplum** [comment]
Thank for your contribution. I will make some small changes then.

**Pull request merged**
